echo TCZCCCCCCCCCCCCCCCCCCCCCCCCUCAAGAZUGUUACGAAUAUAGUCGGGGGUUCUAUC> 1kb.txt
for /L %%i in (1,1,4) do type 1kb.txt >> 1kb.txt
echo TCZCCCCCCCCCCCCCCCCCCCCCCCCUCAAGAZUGUUACGAAUAUAGUCGGGGGUUCUAUC> 2kb.txt
for /L %%i in (1,1,5) do type 2kb.txt >> 2kb.txt
echo TCZCCCCCCCCCCCCCCCCCCCCCCCCUCAAGAZUGUUACGAAUAUAGUCGGGGGUUCUAUC> 4kb.txt
for /L %%i in (1,1,6) do type 4kb.txt >> 4kb.txt
echo TCZCCCCCCCCCCCCCCCCCCCCCCCCUCAAGAZUGUUACGAAUAUAGUCGGGGGUUCUAUC> 8kb.txt
for /L %%i in (1,1,7) do type 8kb.txt >> 8kb.txt
echo TCZCCCCCCCCCCCCCCCCCCCCCCCCUCAAGAZUGUUACGAAUAUAGUCGGGGGUUCUAUC> 16kb.txt
for /L %%i in (1,1,8) do type 16kb.txt >> 16kb.txt
echo TCZCCCCCCCCCCCCCCCCCCCCCCCCUCAAGAZUGUUACGAAUAUAGUCGGGGGUUCUAUC> 32kb.txt
for /L %%i in (1,1,9) do type 32kb.txt >> 32kb.txt
echo TCZCCCCCCCCCCCCCCCCCCCCCCCCUCAAGAZUGUUACGAAUAUAGUCGGGGGUUCUAUC> 64kb.txt
for /L %%i in (1,1,10) do type 64kb.txt >> 64kb.txt
echo TCZCCCCCCCCCCCCCCCCCCCCCCCCUCAAGAZUGUUACGAAUAUAGUCGGGGGUUCUAUC> 128kb.txt
for /L %%i in (1,1,11) do type 128kb.txt >> 128kb.txt
echo TCZCCCCCCCCCCCCCCCCCCCCCCCCUCAAGAZUGUUACGAAUAUAGUCGGGGGUUCUAUC> 256kb.txt
for /L %%i in (1,1,12) do type 256kb.txt >> 256kb.txt